- name: Ensuring some cli tools are available for wrapper scripts
  ansible.builtin.yum:
    name: "{{ zabbix_cli_pkgs }}"
    state: installed

- name: Directory structure for zabbix-cli
  ansible.builtin.file:
    path: /etc/zabbix-cli
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Template for zabbix-cli
  ansible.builtin.template:
    src: zabbix-cli.conf.j2
    dest: /etc/zabbix-cli/zabbix-cli.conf

- name: Auth files for zabbix-cli/zapi-tools scripts
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/root/.{{ item }}"
    owner: root
    group: root
    mode: 0400
  with_items:
    - zabbix-cli_auth
    - zapi-tools.yaml

- name: Distributing some script for Zabbix API automation
  ansible.builtin.template:
    src: "scripts/{{ item }}.j2"
    dest: "/usr/libexec/centos/{{ item }}"
    owner: root
    group: root
    mode: 0750
  with_items:
    - zapi-inventory-update
    - zapi-update-agent-psk
    - zabbix_host_tool
