---
# tasks file for zabbix-server


- name: Importing specific distro variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - vars

- block:
    - name: Creating mandatory DB 
      include_role: 
        name: mysql
        tasks_from: db_remote
      vars:
        db_user: "{{ zabbix_db_user }}"
        db_pass: "{{ zabbix_db_pass }}"
        db_name: "{{ zabbix_db_name }}"
        db_encoding: utf8mb4
        db_collation: utf8mb4_bin
 
    - name: Opening iptables if needed on remote mysql host
      include_role: 
        name: iptables
        tasks_from: remote-mysqld
  when: use_remote_mysql_host
  delegate_to: "{{ mysql_host }}"

- ansible.builtin.include_role:
    name: mysql
  when: not use_remote_mysql_host

- name: Creating mandatory (local) Zabbix DB 
  include_role: 
    name: mysql
    tasks_from: db
  vars:
    mysql_db_user: "{{ zabbix_db_user }}"
    mysql_db_pass: "{{ zabbix_db_pass }}"
    mysql_db_name: "{{ zabbix_db_name }}"
    mysql_db_encoding: utf8mb4
    mysql_db_collation: utf8mb4_bin
  when: not use_remote_mysql_host
  tags:
    - db

- name: Configuring httpd
  ansible.builtin.include_role:
    name: httpd

- name: Configuring https
  ansible.builtin.include_role:
    name: httpd
    tasks_from: tls

- block:
    - ansible.builtin.include_role:
        name: httpd
        tasks_from: scl-php
    - name: Installing some PHP pkgs from SCL (el7)
      yum: 
        name: "{{ zabbix_php_pkgs }}"
        state: latest
      notify: restart_httpd  
    # Removing (for upgrade case) some pkgs before installing new ones (strange deps loop)
    - name: Cleaning up non SCL pkgs before installing new ones (el7)
      ansible.builtin.yum:
        name: zabbix-web-mysql
        state: removed
    # Fix for php73 it doesn't seem provided in zabbix rpm but it was for php72
    - name: Configuring php73-fpm for zabbix
      ansible.builtin.template:
        src: rh-php73-fpm-zabbix.conf.j2
        dest: /etc/opt/rh/rh-php73/php-fpm.d/zabbix.conf
      notify: restart_rh_php73_fpm
  when: ansible_distribution_major_version == '7'


- name: Installing required pkgs for Zabbix
  ansible.builtin.yum:
    name: "{{ zabbix_server_pkgs }}"
    state: latest

- name: Specific config for php73/scl (el7)
  ansible.builtin.template:
    src: httpd-php-zabbix.conf.j2
    dest: /etc/httpd/conf.d/zabbix.conf
  notify: restart_httpd  
  when: ansible_distribution_major_version == '7'
    
- name: Ensuring php-fpm service is started
  ansible.builtin.service:
    name: php-fpm
    state: started
    enabled: True
  when: ansible_distribution_major_version >= '8'
  tags:
    php-fpm

- name: Importing mysql schema if needed
  community.mysql.mysql_db:
    name: "{{ zabbix_db_name }}"
    state: import
    target: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
  when: mysql_created_db.changed
  tags:
    - db

- include_tasks: selinux.yml

- name: Configuring zabbix server
  ansible.builtin.template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    mode: 0644
  notify: restart_zabbix_server
 
- name: Ensuring Zabbix server is started
  ansible.builtin.service:
    name: zabbix-server
    state: started
    enabled: True          

- name: Configure Zabbix web UI
  ansible.builtin.template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    mode: 0644

- include_tasks: cli.yml

- name: Configuring http vhost
  ansible.builtin.template:
    src: httpd-zabbix.conf.j2
    dest: /etc/httpd/conf.d/02_zabbix.conf
    mode: 0644
  notify: restart_httpd 

# https is needed
- name: Distributing TLS keys
  ansible.builtin.include_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ zabbix_httpd_vhost_name }}"
  when: zabbix_httpd_tls_redirect
  tags:
    - tls

- name: Configuring https vhost
  ansible.builtin.template:
    src: httpd-ssl-zabbix.conf.j2
    dest: /etc/httpd/conf.d/ssl-02_zabbix.conf
    mode: 0644
  notify: restart_httpd 
  when: zabbix_httpd_tls_redirect
 
# Iptables rules
- name: Allowing src ip to reach zabbix server
  ansible.builtin.include_role:
    name: iptables
    tasks_from: custom-policy-list
  vars:
    iptables_policy_name: zabbix-server
    iptables_protocol: tcp
    iptables_port: 10051
    iptables_allowed_from: "{{ zabbix_iptables_from }}"

# Custom zabbix scripts
- include_tasks: scripts.yml

# Backup
- name: Ensuring backup user and jobs
  ansible.builtin.include_role:
    name: centos-backup
    tasks_from: client

- ansible.builtin.include_role:
    name: postfix
    tasks_from: relay_to
  vars:
    postfix_relay_to: True  
    
